spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 34165
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
