spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/BankCardDatabaseDocker
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
