CREATE TABLE PERSON (
                        ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        SURNAME varchar(30) NOT NULL,
                        NAME varchar(30) NOT NULL,
                        BIRTHDAY DATE
);

CREATE TABLE Account (
                         ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         CARD_NUMBER varchar(16) NOT NULL UNIQUE,
                         BALANCE bigint,
                         ISSALARY bool,
                         PERSON_ID int REFERENCES Person(id) ON DELETE SET NULL
);