CREATE TABLE PERSON (
                        ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        SURNAME varchar(30) NOT NULL,
                        NAME varchar(30) NOT NULL,
                        BIRTHDAY DATE
);

CREATE TABLE ACCOUNT (
                         ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         CARD_NUMBER VARCHAR(16) NOT NULL UNIQUE,
                         BALANCE BIGINT,
                         ISSALARY BOOL,
                         PERSON_ID int REFERENCES PERSON(ID) ON DELETE SET NULL
);